version: "3.8"

services:
  webapi:
    build:
      context: ./Gestion-des-RDVs-webapi
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    environment:
      - DOCKER_BUILDKIT=1
    ports:
      - "8080:8080"
    depends_on:
      - db
  webapp:
    build:
      context: ./Gestion-des-RDVs-webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webapi
    environment:
      REACT_APP_API_URL: http://webapi:8080
      REACT_APP_ENV: qa

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: RDV
    ports:
      - "5432:5432"